version: '3.8'
name: noauth-backend

services:
  db:
    image: postgres:15.1-alpine3.17
    ports:
      - 5433:5432
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data/

volumes:
  db-data:
